<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-15T19:50:33 CDT" name="Default suite" finished-at="2023-06-15T19:50:45 CDT" duration-ms="11911">
    <groups>
    </groups>
    <test started-at="2023-06-15T19:50:33 CDT" name="Default test" finished-at="2023-06-15T19:50:45 CDT" duration-ms="11911">
      <class name="TestCases.DemoTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestCases.DemoTest@127f9161]" started-at="2023-06-15T19:50:33 CDT" name="setUp" finished-at="2023-06-15T19:50:37 CDT" duration-ms="4623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Logo()[pri:1, instance:TestCases.DemoTest@127f9161]" started-at="2023-06-15T19:50:38 CDT" name="Logo" finished-at="2023-06-15T19:50:38 CDT" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logo -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestCases.DemoTest@127f9161]" started-at="2023-06-15T19:50:38 CDT" name="TearDown" finished-at="2023-06-15T19:50:38 CDT" duration-ms="328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestCases.DemoTest@127f9161]" started-at="2023-06-15T19:50:38 CDT" name="setUp" finished-at="2023-06-15T19:50:40 CDT" duration-ms="2303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Login()[pri:2, instance:TestCases.DemoTest@127f9161]" started-at="2023-06-15T19:50:40 CDT" name="Login" finished-at="2023-06-15T19:50:42 CDT" duration-ms="1144" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [invalid msgs] but found [Login was unsuccessful. Please correct the errors and try again.
No customer account found]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [invalid msgs] but found [Login was unsuccessful. Please correct the errors and try again.
No customer account found]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestCases.DemoTest.Login(DemoTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestCases.DemoTest@127f9161]" started-at="2023-06-15T19:50:42 CDT" name="TearDown" finished-at="2023-06-15T19:50:42 CDT" duration-ms="349" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestCases.DemoTest@127f9161]" started-at="2023-06-15T19:50:42 CDT" name="setUp" finished-at="2023-06-15T19:50:44 CDT" duration-ms="2370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Register()[pri:3, instance:TestCases.DemoTest@127f9161]" started-at="2023-06-15T19:50:44 CDT" name="Register" finished-at="2023-06-15T19:50:44 CDT" duration-ms="9" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method DemoTest.Register()[pri:3, instance:TestCases.DemoTest@127f9161] should have thrown an exception of type class org.testng.SkipException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method DemoTest.Register()[pri:3, instance:TestCases.DemoTest@127f9161] should have thrown an exception of type class org.testng.SkipException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Register -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestCases.DemoTest@127f9161]" started-at="2023-06-15T19:50:44 CDT" name="TearDown" finished-at="2023-06-15T19:50:45 CDT" duration-ms="286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- TestCases.DemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
